#---------------------------------------#

@host=localhost
@port=5027
@hostname=http://{{host}}:{{port}}

#---------------------------------------#

# Post

### Obtener todos los post
GET {{hostname}}/posts

### Uso de queryParams
GET {{hostname}}/posts?take=2

### Obtener post por id
GET {{hostname}}/post/75518435-ae56-489c-b557-056a9050b5f4

### Crear un post y guardarlo en la base de dato
POST {{hostname}}/post/create
Content-Type: Application/json

{
  "title": "Formatear un archivo JSON usando 'json_pp'",
  "content": "La herramienta `json_pp` se usa para formatear JSONs, se puede usar de esta forma: `archivo.json | json_pp`"
}

### Actualizar un post
### TODO: Realizar esta acción

### Eliminar un post por id
DELETE {{hostname}}/posts/delete/9cb8c8c6-820a-4a4b-b299-027e80dd0a8b

### Blogs

## Obtener todos los blogs
GET {{hostname}}/blogs

## Obtener un blog por id
GET {{hostname}}/blogs/get-one/dcd69cf8-d5c8-4dc3-8a6e-08cffa3cd47c

## Crear un blog
POST {{hostname}}/blog/create
Content-Type: Application/json

{
  "url": "https://sdasdasda"
}

## Actualizar un blog
PATCH {{hostname}}/blog/update
Content-Type: Application/json

{
  "id": "17febbd0-8503-44bc-973e-cf558e348e55",
  "url": "https://dev.to/vuejs"
}

## Eliminar un blog
DELETE {{hostname}}/blog/delete/17febbd0-8503-44bc-973e-cf558e348e55

