version: "3.3"

services:
  #app:
  #  image: dotnet_8
  #  container_name: csharp_app
  #  ports:
  #    - 8000:5000

  #  working_dir: /app
  #  volumes:
  #    - /home/lauta/dev/dotNet/project-test/Escuela/:/app

  #  command: bash /app/init_app.sh -w

  db:
    image: postgres:alpine
    restart: always
    container_name: postgres
    # set shared memory limit when using docker-compose
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example

    ports:
      - 8001:5432

    volumes:
      - data:/var/lib/postgresql/data
      - ./scripts/backup.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  data:
